### ISSUE TITLE
wxFormBuilder operation

### ISSUE THREAD

**Issue by rgleason** [transmitterdan/BatchUTILS#2]
I'd like to fix the weatherfax_pi opening menu for the weatherfax internetretrieval menu. Why? The main buttons to initiate retrival are hidden when the menu is opened and are not exposed when the menu is expaned vertically! They are only exposed when the middle bar is pulled up!!

This is a major inconvience and is also a huge hurdle to new users learning the plugin.

I have tried to reconfigure the wxformbuilder fbp file and save the fbp file. Then recompiled the plugin and copied the debug versaion of weatherfax_pi to github/opencpn/plugin for testing and I find nothing about the menu has changed. 

Is there some other action that must be taken? Can someone please explain the correct prcedure to get changes in wxformbuilder into the plugin?

Thankyou

**Comment by rgleason** [comment]
In fact Sean said "oh that's not not good, someone should fix that!" when he understood the problem.

**Comment by rgleason** [comment]
Figured it out. See below. Will make pull request with the improvements to the form later

http://www.cruisersforum.com/forums/showthread.php?p=2476195

**Comment by rgleason** [comment]
I think this is done, but perhaps we keep it open so I can add a page in Dev - plugins

**Comment by transmitterdan** [comment]
Rick,

In Windows its very hard to have generic development instructions. Too many people can't or don't want to install VS2013. Most developers have moved up to VS2017 by now. But it isn't compatible with VS2013 built DLLs in some cases. I think the best we can do is offer to help people get their particular environment setup with a work flow that is best for them. I'm happy to help others get a development environment running. Probably we should just try to explain the work flow for VS2013 and tell everyone that is what we use. If others don't want to use VS2013 then they are mostly on their own but some of us will help them. I can use any compiler (13, 15 17) to compile O using any version of wxWidgets (3.0.2, 3.0.3 or 3.1). But I have no idea how to tell someone else how to do that because everyone has their own workflow they want to use
